// ─────────────────────────────────────────────────────────────────────────────
// Centralized car catalog with accurate 2024 ex-showroom prices (India)
// and model-accurate car images
// ─────────────────────────────────────────────────────────────────────────────
export const CARS = [
  {
    id: 1,
    name: 'Maruti Swift ZXi+',
    // 2024 ex-showroom Delhi price
    price: '₹ 9,04,000',
    year: 2024,
    mileage: '9,500 km',
    type: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Manual / AMT',
    engine: '1.2L K-Series DualJet',
    power: '89 bhp',
    torque: '113 Nm',
    seating: 5,
    color: 'Pearl Arctic White',
    // Accurate: compact sporty hatchback (Maruti Swift look-alike)
    image: '/car-swift.jpg',
    description: 'Popular city hatchback with peppy performance and efficient mileage.',
    longDesc: "The Maruti Swift ZXi+ is India's favourite hatchback, now better than ever. With its sporty design, segment-leading fuel efficiency of 23.76 km/l, and advanced features like 6 airbags, ESP, and a 9-inch SmartPlay Pro+ infotainment system, the Swift is the perfect urban companion. The dual-jet engine delivers a smooth, refined drive in city traffic and on highways alike.",
    highlights: ['6 Airbags', 'ESP & Hill Hold', '9-inch SmartPlay Pro+', 'Auto Gear Shift', 'LED Projector Headlamps', 'Wireless Android Auto / Apple CarPlay'],
    badge: 'Best Seller',
    accentColor: '#ef4444',
    emi: '₹ 16,800/mo',
  },
  {
    id: 2,
    name: 'Tata Nexon XZ+',
    price: '₹ 13,49,900',
    year: 2024,
    mileage: '11,200 km',
    type: 'SUV',
    fuel: 'Petrol / Diesel',
    transmission: '6-Speed Manual / AMT',
    engine: '1.2L Turbocharged Petrol',
    power: '120 bhp',
    torque: '170 Nm',
    seating: 5,
    color: 'Daytona Grey',
    image: '/car-nexon.jpg',
    description: 'Compact SUV with high safety ratings, premium interior, and smart features.',
    longDesc: "The Tata Nexon XZ+ has earned the distinction of being India's first 5-star Global NCAP-rated car. Its bold tri-arrow design language turns heads wherever it goes. Inside, a premium leatherette cabin with ambient lighting and a 10.25-inch floating touchscreen keep both driver and passengers delighted.",
    highlights: ['5-Star Global NCAP Safety', '10.25" Floating Infotainment', 'Air Purifier', 'Wireless Charging', 'Sunroof', 'ISOFIX Child Seat Mounts'],
    badge: '5-Star Safety',
    accentColor: '#3b82f6',
    emi: '₹ 25,200/mo',
  },
  {
    id: 3,
    name: 'Mahindra Thar AX (O)',
    price: '₹ 16,79,000',
    year: 2025,
    mileage: '7,800 km',
    type: 'Off-Road',
    fuel: 'Diesel',
    transmission: '6-Speed Manual / 6AT',
    engine: '2.2L mHawk Diesel',
    power: '132 bhp',
    torque: '320 Nm',
    seating: 4,
    color: 'Napoli Black',
    image: '/car-thar.jpg',
    description: 'Rugged off-roader with a bold design and excellent terrain capability.',
    longDesc: "The Mahindra Thar is more than just a vehicle — it's a lifestyle statement. Engineered for adventure seekers, the Thar AX features a class-leading 4x4 drivetrain with 4LO mode, making it unstoppable on rocky trails, river crossings, and steep inclines. The massive 220mm ground clearance ensures no terrain is too tough.",
    highlights: ['4x4 with 4LO Mode', '220mm Ground Clearance', 'Adventure Statistics Display', 'Removable Soft Top / Hard Top', 'Rear Camera & Parking Sensors', 'Drive Modes: Grass, Gravel, Sand, Rock'],
    badge: 'Adventure King',
    accentColor: '#84cc16',
    emi: '₹ 31,400/mo',
  },
  {
    id: 4,
    name: 'Hyundai Creta SX(O)',
    price: '₹ 18,11,000',
    year: 2024,
    mileage: '13,600 km',
    type: 'SUV',
    fuel: 'Petrol / Diesel',
    transmission: '6-Speed Manual / IVT / DCT',
    engine: '1.5L MPi Petrol',
    power: '115 bhp',
    torque: '144 Nm',
    seating: 5,
    color: 'Abyss Black Pearl',
    image: '/car-creta.png',
    description: 'Stylish mid-size SUV offering spacious comfort and modern connectivity.',
    longDesc: "The Hyundai Creta SX(O) redefined the mid-size SUV segment with its bold design and technology-first philosophy. The all-new 2024 Creta features a panoramic sunroof, Level 2 ADAS, and a segment-first dual-screen cockpit with a 10.25-inch digital cluster. With BlueLink connected car tech and 60+ features, it is the smartest car in its class.",
    highlights: ['Level 2 ADAS', 'Dual 10.25" Screens', 'Panoramic Sunroof', 'BlueLink Connected Car', 'Ventilated Front Seats', '6 Airbags + ESC'],
    badge: "Editor's Choice",
    accentColor: '#a855f7',
    emi: '₹ 33,900/mo',
  },
  {
    id: 5,
    name: 'Kia Seltos GTX+',
    price: '₹ 19,45,000',
    year: 2024,
    mileage: '10,300 km',
    type: 'SUV',
    fuel: 'Petrol / Diesel',
    transmission: '6-Speed Manual / DCT / AT',
    engine: '1.5L Turbo GDi',
    power: '140 bhp',
    torque: '242 Nm',
    seating: 5,
    color: 'Glacier White Pearl',
    image: '/car-seltos.jpg',
    description: 'Feature-rich SUV with a premium cabin and strong road presence.',
    longDesc: "The Kia Seltos GTX+ is a statement of premium engineering and bold design. The segment's most powerful engine produces 140 bhp and 242 Nm of torque, paired with a 7-speed DCT. Inside, the Bose Premium Sound System with 8 speakers, the panoramic curved display, and ambient mood lighting create an atmosphere of pure luxury.",
    highlights: ['140 bhp Turbo Engine', 'Bose 8-Speaker System', 'Panoramic Curved Display', '360° Surround View Monitor', 'Highway Drive Assist', 'Electric Parking Brake'],
    badge: 'Premium Pick',
    accentColor: '#f59e0b',
    emi: '₹ 36,400/mo',
  },
  {
    id: 6,
    name: 'Toyota Innova Crysta GX+',
    price: '₹ 20,69,000',
    year: 2024,
    mileage: '18,900 km',
    type: 'MPV',
    fuel: 'Diesel',
    transmission: '5-Speed Manual / 6-Speed AT',
    engine: '2.4L GD Series Diesel',
    power: '148 bhp',
    torque: '343 Nm',
    seating: 7,
    color: 'Super White',
    image: '/car-innova.png',
    description: 'Spacious MPV ideal for families with refined comfort and reliability.',
    longDesc: "The Toyota Innova Crysta GX+ is the benchmark for premium MPVs in India. With 7 captain seats, an exceptionally refined diesel engine producing 343 Nm of torque, and Toyota's legendary reliability, the Crysta is the preferred choice of families and executives alike.",
    highlights: ['7 Captain Seats', '343 Nm Diesel Torque', 'Dual Zone Climate Control', '9" Touchscreen + JBL Audio', '7 Airbags', 'Vehicle Stability Control'],
    badge: 'Family Choice',
    accentColor: '#06b6d4',
    emi: '₹ 38,700/mo',
  },
];
